### ISSUE TITLE
The localization result of inpainted image is very confusion,why?

### ISSUE THREAD

**Issue by 1129179891ljc** [lihaod/Deep_inpainting_localization#3]
![e2d1284d5630a622c1967633cf3a72c](https://user-images.githubusercontent.com/38351525/113979533-f3939e00-9877-11eb-93c2-17fdc2011118.png)

**Comment by lihaod** [comment]
It may be due to the fact that the trained model was not properly loaded.
Use --restore to specify the path of trained model, e.g., "--restore ./ckpt/jpg75/model.ckpt".
