### ISSUE TITLE
Question on the dataset structure

### ISSUE THREAD

**Issue by sejmoonwei** [lihaod/Deep_inpainting_localization#4]
I set   'data_dir' = ./train
The folder train is organized as :
– train 
  |– JPG 
    |–1.jpg
    |–2.jpg
    ……
  |– MASK
    |–1.png
    |–2.png
    ……
as python raises error, I guess there's something wrong with the traindata. Could you please specify the correct structure for the train folder?   Do appreciate your great work

**Comment by xueyaosmile** [comment]
> I set 'data_dir' = ./train The folder train is organized as : – train   |– JPG     |–1.jpg     |–2.jpg     ……   |– MASK     |–1.png     |–2.png     …… as python raises error, I guess there's something wrong with the traindata. Could you please specify the correct structure for the train folder? Do appreciate your great work

hi, I encountered the same problem as you, how did you solve it?
