### ISSUE TITLE
Dataset Compressed file is Corrupted

### ISSUE THREAD

**Issue by teamwong111** [lihaod/Deep_inpainting_localization#8]
Thanks for your great work!

I download your dataset according to the link https://pan.baidu.com/s/1Df77EOoBkhukLNAz3YKT4w?pwd=gi60. There are 5 compressed files `test.tar.gz`, `train.tar.gz.aa`, `train.tar.gz.ab`, `train.tar.gz.ac`, `train.tar.gz.ad`, but `train.tar.gz.ab`, `train.tar.gz.ac`, `train.tar.gz.ad` are completely corrupted, and `train.tar.gz.aa` is partially corrupted where i only can get 1100 QF96 images.

The error report in command line like this
```
$ tar -xzf train.tar.gz.aa 

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Wish for your reply, thanks

**Comment by lihaod** [comment]
```
$ cat train.tar.gz.a* >> train.tar.gz
$ tar -xzf train.tar.gz
```
